fix: compatibility check not working in bash
wfxr/forgit pull request #258
Opened 2022-12-06 12:26 UTC by gbtec-markusmeier

fixes https://github.com/wfxr/forgit/issues/256
and https://github.com/wfxr/forgit/issues/257

## Check list

- [x] I have performed a self-review of my code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Description

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

Fixes:
* https://github.com/wfxr/forgit/issues/256
* https://github.com/wfxr/forgit/issues/257

2022-12-07 11:57 UTC, carlfriedrich requested changes
@gbtec-markusmeier Thanks a lot for your bug reports and this fix. Do I understand it correctly that this solution only fixes the situation for `bash`? Do we need a different behavior for `zsh`?

2022-12-07 11:57 UTC, carlfriedrich commented on forgit.plugin.zsh
> +[[ -n "$BASH_VERSION" ]] && set -o posix
Maybe it would be good to add a describing comment here why we're calling `set -o posix`.

2022-12-07 12:32 UTC, gbtec-markusmeier commented
> @gbtec-markusmeier Thanks a lot for your bug reports and this fix. Do I understand it correctly that this solution only fixes the situation for `bash`? Do we need a different behavior for `zsh`?

Zsh works fine, we don't have that problem there: zsh reports only variables when calling `set`.

2022-12-09 08:49 UTC, carlfriedrich approved these changes
@gbtec-markusmeier Great, thanks a lot. Since it works for me as well in both shells, I will directly merge this. In fish this hasn't been reported as a problem so far.

2022-12-09 08:54 UTC, merged