Allow passing parameters to forgit::reset::head
wfxr/forgit pull request #309
Opened 2023-05-26 18:43 UTC by sandr01d

## Check list

- [X] I have performed a self-review of my code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Description

Allow passing parameters to forgit::reset::head in the same way we already do for most other functions.

## Type of change

- [ ] Bug fix
- [X] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [X] bash
    - [X] zsh
    - [X] fish
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

2023-05-30 09:31 UTC, carlfriedrich requested changes

2023-05-30 19:32 UTC, sandr01d commented
Must have overlooked that, good catch! I've made changes accordingly.

2023-05-31 07:48 UTC, carlfriedrich requested changes

2023-05-31 07:48 UTC, carlfriedrich commented on bin/git-forgit
Great, thanks for the update, but now you missed the argument. :-)

2023-05-31 17:11 UTC, sandr01d commented
Guess I should code when tired. Third time's the charm :)

2023-05-31 19:17 UTC, carlfriedrich commented
> Guess I shouldn't code when tired. Third time's the charm :)

That's what reviews are for. :-)

Great addition, thanks a lot for your contribution!

2023-05-31 19:18 UTC, merged