Add new workflow to update homebrew formula on release
wfxr/forgit pull request #341
Opened 2024-02-01 17:01 UTC by cjappl

This workflow was found here:

https://github.com/dawidd6/action-homebrew-bump-formula

This should be very similar to our AUR workflow, which can be seen here:
https://github.com/wfxr/forgit/blob/ab7400ddb37c758b8247ce0884cd2283a873e258/.github/workflows/aur.yaml#L1-L20

I am writing an email to @wfxr asking him to add a TOKEN to our secrets with the appropriate permissions so this can run :)

2024-02-01 17:24 UTC, carlfriedrich requested changes
@cjappl Great stuff, thanks for checking this out!

2024-02-01 17:24 UTC, carlfriedrich commented on .github/workflows/brew.yaml
> +  aur:
This job should be called "brew" or something similar.

2024-02-01 17:24 UTC, carlfriedrich commented on .github/workflows/brew.yaml
> +          token: ${{secrets.TOKEN}}
And the token should probably be called `HOMEBREW_TOKEN` to make its purpose clear.

2024-02-01 19:44 UTC, carlfriedrich approved these changes

2024-02-01 19:46 UTC, carlfriedrich commented
@cjappl Thanks for the quick fixes.
Just being curious: did you generate a personal access token in your account for this purpose, so that the automatic brew commits will be done in your name?

2024-02-01 19:57 UTC, cjappl commented
> @cjappl Thanks for the quick fixes. Just being curious: did you generate a personal access token in your account for this purpose, so that the automatic brew commits will be done in your name?

No, I could, but it's probably safer from a security side to have wfxr do it (just so I don't have to send one of my tokens in plaintext to him via email or similar). He is still the one that must update any secrets or other Settings of this project, as it's under his name.

I would expect the commits likely end up under his user account in that case!

2024-02-02 02:31 UTC, wfxr approved these changes
LGTM.

@cjappl BREW_TOKEN has been set.

2024-02-02 03:23 UTC, cjappl commented
Thanks @wfxr ! Will merge sometime tomorrow.

2024-02-02 18:28 UTC, merged

2024-02-02 19:14 UTC, carlfriedrich commented
@cjappl Did you merge into `FixZshCompletions` on purpose?

2024-02-02 19:37 UTC, cjappl commented
Whoa. No I did not. Thank you for catching..... Let me fix that

2024-02-02 19:40 UTC, cjappl commented
Great catch @carlfriedrich . would you please review #342 and #340 to make sure they are both as you expect them to be?