Refactor: Replace deferred code in edit commands with functions
wfxr/forgit pull request #361
Opened 2024-03-06 21:19 UTC by sandr01d

## Check list

- [X] I have performed a self-review of my code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Description

`_forgit_diff` and `_forgit_add` allow editing the currently previewed file in the `EDITOR`. This used to be handled entirely using deferred code. This PR replaces the deferred code and binds the commands to functions instead.

### Note                                                                                                            
                                                                                                                      
This PR belongs to #326 and resulted from discussions in #324.

## Type of change

- [ ] Bug fix
- [ ] New feature
- [X] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

2024-03-06 21:21 UTC, sandr01d commented
@carlfriedrich Scratch my earlier comment about doing `_forgit_extract_sha` first. Looking into this I figured that doint the `execute-silent` commands first will add less friction.

2024-03-07 15:52 UTC, tjaacks requested changes
@sandr01d Thanks for the new PR! Just two small comments, rest LGTM.

2024-03-07 15:52 UTC, tjaacks commented on bin/git-forgit
> +        --bind=\"alt-e:execute($FORGIT edit_diffed_file {})+refresh-preview\"
This should stay `execute-silent`, shouldn't it?

2024-03-07 15:52 UTC, tjaacks commented on bin/git-forgit
> +    $EDITOR "$(echo "$1" | _forgit_get_single_file_from_add_line)" >/dev/tty </dev/tty
This has been implemented as a one-liner, whereas `_forgit_edit_diffed_file()` has split the nearly identical work into three (better readable) lines. We should transform this accordingly to have the same style in both functions.

2024-03-07 16:16 UTC, carlfriedrich requested changes
@sandr01d Thanks for the new PR! Just two small comments, rest LGTM.

2024-03-07 16:16 UTC, carlfriedrich commented on bin/git-forgit
> +    $EDITOR "$(echo "$1" | _forgit_get_single_file_from_add_line)" >/dev/tty </dev/tty
This has been implemented as a one-liner, whereas `_forgit_edit_diffed_file()` has split the nearly identical work into three (better readable) lines. We should transform this accordingly to have the same style in both functions.

2024-03-07 16:16 UTC, carlfriedrich commented on bin/git-forgit
> +        --bind=\"alt-e:execute($FORGIT edit_diffed_file {})+refresh-preview\"
This should stay `execute-silent`, shouldn't it?

2024-03-07 22:44 UTC, sandr01d commented
Good finds @carlfriedrich, thanks! I've implemented as requested. Rerequesting your review.

2024-03-07 22:50 UTC, carlfriedrich approved these changes
Great, thanks for the update!

2024-03-24 14:56 UTC, sandr01d commented
Changes have been merged with #326

2024-03-24 14:56 UTC, closed without merging